### ISSUE TITLE
Genre + Question

### ISSUE THREAD

**Issue by BzowK** [makkoncept/yts.am_scraper_#3]
Hey - 

Found your script tonight and it's interesting.  It worked well for me, but I had to comment out 'print' lines to get it to work plus it automatically added "b...'" around every value in CSV.  Removing that plus moving the year to a separate column is easy enough in Excel, though.  Personally, I would find it very helpful if it added a Genre(s) column which I did see was usually the 2nd h2 value in the page source, but only checked a handful. 

Quick Question:  The reason I came across it is that I am trying to script something I think many would find useful, yet am more of a PowerShell person due to work.  I recently created a CSV which lists all sub-1080p titles I own with their name in the first column and year produced in the 2nd column.  What I'd like to be able to do is use it as a source for a script which would cross-reference each title/year with what your script produces and if a 1080p torrent is found, download it, add to queue, whatever.

Are you familiar with a script that would do this or have suggestions for setting one up?  Thanks!

**Comment by makkoncept** [comment]
hi @BzowK, thanks for the feedback. I have made some changes to the script. There is now a genre column and also movie name and year are split into different columns.

There can be many ways to do this in python. One of them would be that you create dictionaries from two csv files ([stackoverflow](https://stackoverflow.com/questions/6740918/creating-a-dictionary-from-a-csv-file)) and then 'subtract' them([stackoverflow](https://stackoverflow.com/a/35187281)). 
There is already `data.csv` in repository which you can use.
