### ISSUE TITLE
NameError: name 'torrent_1080' is not defined

### ISSUE THREAD

**Issue by BzowK** [makkoncept/yts.am_scraper_#4]
Hey - 

Just a note that i attempted running your script today and it almost immediately resulted in the below error when grabbing the 1st title:
...
Traceback (most recent call last):
  File "yify_browse.py", line 76, in <module>
    print("1080p torrent:", torrent_1080)
NameError: name 'torrent_1080' is not defined

It seemingly grabbed all of the other content for the title just fine.  I tried it on a different system, but got the same result.  To note, I'm using Python 3.6, but nothing has changed on the system since the last time it worked.

Any suggestions or do you have the same issue?  Thanks

**Comment by makkoncept** [comment]
hi @BzowK, I have just tested the script. It works for me.
Try cloning a new copy of the repository and run it there.
Also if you want to just download the torrents or only get their download links, use [yts_torrents](https://github.com/makkoncept/yts_torrents). 

Also, check out [movie_torrents](https://github.com/makkoncept/movie_torrents). It has 10k+ torrents of Yify.

**Comment by BzowK** [comment]
Thanks for reply - sorry for my late one...

I did a fresh pull prior to posting but maybe it was a site issue.  Ill try again soon.

Appreciate the suggestion about yts_torrents.  The reason I was using your script was that I was working on a spreadsheet with all the titles I have inc specs,  The plan was to get all titles in sd plus ones which were way too big then cross reference it with a spreadsheet built by your script to get links for 1080 ones as replacements.  Id then use deluge-cli to add them.  So far just replaced all which were 7+gb and plan to do rest soon.  if you have any suggestions, please let me know.

Thanks!
